import {Attributes} from '../Segments';

export const weatherCodeLookupMap = new Map([
  ['clear', new Attributes('Clear', '#eeeef5', '')],
  ['mostly_clear', new Attributes('Partly Cloudy', '#c1c5ce', '')],
  ['partly_cloudy', new Attributes('Partly Cloudy', '#c1c5ce', '#fff')],
  ['mostly_cloudy', new Attributes('Mostly Cloudy', '#a1a2a7', '#fff')],
  ['cloudy', new Attributes('Overcast', '#797f87', '#fff')],
  ['tstorm', new Attributes('Thunderstorms', '#d4d271', '')],
  ['rain_heavy', new Attributes('Heavy Rain', '#3267c7', '#fff')],
  ['rain', new Attributes('Rain', '#4a80c7', '#fff')],
  ['rain_light', new Attributes('Light Rain', '#80a5d6', '#fff')],
  ['drizzle', new Attributes('Drizzle', '#8cacd6', '#fff')],
  ['freezing_rain_heavy', new Attributes('Freezing Heavy Rain', '#486384', '#fff')],
  ['freezing_rain', new Attributes('Freezing Rain', '#6788b2', '#fff')],
  ['freezing_rain_light', new Attributes('Freezing Light Rain', '#80a5d6', '#fff')],
  ['freezing_drizzle', new Attributes('Freezing Drizzle', '#a1ccff', '')],
  ['ice_pellets_heavy', new Attributes('Heavy Hail', '#418284', '#fff')],
  ['ice_pellets', new Attributes('Hail', '#70a1a6', '#fff')],
  ['ice_pellets_light', new Attributes('Light Hail', '#89b9c1', '#fff')],
  ['flurries', new Attributes('Flurries', '#cbb5e2', '')],
  ['snow_light', new Attributes('Light Snow', '#c7a8f3', '')],
  ['snow', new Attributes('Snow', '#d59deb', '')],
  ['snow_heavy', new Attributes('Heavy Snow', '#ae6acb', '#fff')],
  ['fog_light', new Attributes('Light Fog', '#d5dae2', '')],
  ['fog', new Attributes('Fog', '#b6bfcb', '')]
]);

export const lookupWeatherCodeIcon = new Map([
  ['clear', 'clear'],
  ['mostly_clear', 'partly_cloudy'],
  ['partly_cloudy', 'partly_cloudy'],
  ['mostly_cloudy', 'partly_cloudy'],
  ['cloudy', 'overcast'],
  ['tstorm', 'thunderstorm'],
  ['rain_heavy', 'heavy_rain'],
  ['rain', 'rain'],
  ['rain_light', 'light_rain'],
  ['drizzle', 'light_rain'],
  ['freezing_rain_heavy', 'heavy_rain'],
  ['freezing_rain', 'rain'],
  ['freezing_rain_light', 'light_rain'],
  ['freezing_drizzle', 'light_rain'],
  ['ice_pellets_heavy', 'hail'],
  ['ice_pellets', 'hail'],
  ['ice_pellets_light', 'hail'],
  ['flurries', 'snow'],
  ['snow_light', 'snow'],
  ['snow', 'snow'],
  ['snow_heavy', 'snow'],
  ['fog_light', 'overcast'],
  ['fog', 'overcast']
]);
